# **1.파이토치(Pytorch)**

* Pytorch는 tensorflow와 함께 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 python 기반으로 변경한 것이 Pytorch임
* New York 대학교와 Facebook이 공동으로 만들었고, 가장 대중적이으로 널리 사용되는 framework임

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_2 = torch.as_tensor(np_array)   # create view
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_np_2[0, 0] = 10
print(x_np_2)
print(np_array)  # change of view -> change original array

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [7]:
x_np_3 = torch.from_numpy(np_array)    # create view
print(x_np_3)

tensor([[10,  2],
        [ 3,  4]])


In [8]:
x_np_3[0,0] = 11
print(x_np_3)
print(np_array)

tensor([[11,  2],
        [ 3,  4]])
[[11  2]
 [ 3  4]]


In [9]:
# tensor -> ndArray
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [10]:
a = torch.ones(2,3)
print(a)
b = torch.zeros(2,3)
print(b)
c = torch.full((2,3), 2)
print(c)
d = torch.empty(2,3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
i = torch.eye(3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [12]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### **1-2. Tensor 속성**

In [13]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [14]:
# 속성 변경
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
if torch.cuda.is_available():   # cuda: Compute Unified Device Architecture: us GPU
  tensor = tensor.to('cuda')

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
DataType of tensor : torch.int32
Device of tensor : cuda:0


### **1.4 Transpose**

In [26]:
a = torch.arange(16).reshape(2,2,4)
                          #  0 1 2  -> transpose(1,2)
print(a, a.shape)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [17]:
b = a.transpose(1, 2)
#      (2,2,4)  -->  transpose(1,2) --> switch 1, 2 -->  (2, 4, 2)
#       0 1 2
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [27]:
# b = a.transpose()
# print(b, b.shape)

TypeError: ignored

In [20]:
c = a.permute((2, 0, 1))   # no just switching two  --> assign each one. 2->0, 0->1, 1->2
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### **1-5. Tensor 연산**

In [21]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [22]:
print(x + y)
print(x - y)
print(x * y) # 1 찾아보기
print(x / y)
print(x @ y) # 2 찾아보기
print('*' * 30)
print(torch.add(x, y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y)) # 찾아보기

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [23]:
# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y)) # x에 결과를 다시 저장
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [24]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [28]:
sum1 = torch.sum(z, axis=0)
sum2 = torch.sum(z, axis=1)
sum3 = torch.sum(z, axis=-1)  # same as axis=1, because axis=1 is last one
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [29]:
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach()
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])


In [30]:
c = torch.cat([a, b], axis=-1)
print(c, c.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]]) torch.Size([4, 12])
