In [1]:
from konlpy.tag import Komoran
import numpy as np

In [23]:
komoran = Komoran()
#text = "오늘 날씨는 구름이 많아요."
text = "오늘 날씨는 구름과 우주인이 많아요."
#text = "내일 날씨는 비와 번개가 많아요."
#text = "모레 날씨는 태풍과 눈이 많아요."

In [24]:
nouns = komoran.nouns(text)
print(nouns)

['오늘', '날씨', '구름', '우주인']


In [25]:
# make dictionary and give index to words
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
        print(word)
        print(len(dics))
        

print(dics)

오늘
1
날씨
2
구름
3
우주인
4
{'오늘': 0, '날씨': 1, '구름': 2, '우주인': 3}


In [26]:
print(dics.keys())
print(dics['오늘'])
print(dics['날씨'])
print(dics['구름'])

dict_keys(['오늘', '날씨', '구름', '우주인'])
0
1
2


In [27]:
# one-hot encoding
nb_classes = len(dics)
targets = list(dics.values())
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
